version: '3'
services:
 nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./ssl:/etc/nginx/ssl
      - ./wiki/nginx.conf:/etc/nginx/nginx.conf
      - nginx_html:/etc/nginx/html/static
    depends_on:
      - wiki
    networks:
      - app-network
 wiki:
    build: 
      context: ./wiki
      dockerfile: Dockerfile
      #target: development   name as form Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    #command: python manage.py collectstatic
    volumes:
      - ./wiki:/wiki
      - nginx_html:/wiki/static
    ports:
      - "8000:8000"
    networks:
      - app-network
  

networks:
  app-network:
    driver: bridge
volumes:
  nginx_html:
